### ISSUE TITLE
Non-CGO_ENABLED builds desirable

### ISSUE THREAD

**Issue by abourget** [nathanielc/morgoth#31]
I'm trying to use the GitHub `releases` but it seems the Linux build for amd64 has dependencies.. I wanted to use it in `alpine` alonside the standard alpine-based `kapacitor` image..

```
/ # ldd /usr/bin/morgoth
	/lib64/ld-linux-x86-64.so.2 (0x558cd1924000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x558cd1924000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x558cd1924000)
```

**Comment by nathanielc** [comment]
Good point, this should be as simple as `CGO_ENABLED=0` for the `gox` command in the travis config. That would force all builds to be static builds. 

I'll need to do some basic testing but Morgoth is pretty simple so I don't expect using static builds for all platforms to cause any issues.

**Comment by nathanielc** [comment]
@abourget I just cut a v0.2.1 release that uses static builds. Otherwise not changes were made.

**Comment by abourget** [comment]
great thanks a million times :)
