### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by sandramadhu** [nathanielc/morgoth#45]
Hi,

I'm seeing an error while installing Morgoth. Any idea?

`go get github.com/nathanielc/morgoth/cmd/morgoth`

Error:
`# github.com/nathanielc/morgoth/cmd/morgoth
../go_workspace/src/github.com/nathanielc/morgoth/cmd/morgoth/main.go:43: cannot use h (type *Handler) as type agent.Handler in assignment:
	*Handler does not implement agent.Handler (missing Snapshot method)
../go_workspace/src/github.com/nathanielc/morgoth/cmd/morgoth/main.go:90: cannot use h (type *Handler) as type agent.Handler in assignment:
	*Handler does not implement agent.Handler (missing Snapshot method)`

**Comment by nathanielc** [comment]
@sandramadhu Thanks, there was a small change fixed upstream. I'll push a fix for this a bit.

**Comment by sandramadhu** [comment]
Thank you.

**Comment by PratikSavadi** [comment]
I'm seeing an error while installing Morgoth. Any idea?

go get github.com/nathanielc/morgoth/cmd/morgoth

go get github.com/nathanielc/morgoth/cmd/morgoth: mkdir /opt/go_path/bin/: permi                                                                                        ssion denied
