### ISSUE TITLE
duplicate metrics collector registration attempted

### ISSUE THREAD

**Issue by avdhoot** [nathanielc/morgoth#56]
created issue to track coming fix. more [info](https://community.influxdata.com/t/kapacitor-morgoth-alert-on-derivative-being-0/1742/7) 
Error msg:
`Error: morgoth3: failed to register metrics for group: "cid=2,cpu=cpu-total,host=p0-c2-xyz.com,region=us-west-2,role=proxy": window count metric: duplicate metrics collector registration attempted’`

**Comment by nathanielc** [comment]
@avdhoot What version are you using when you got this error?

**Comment by avdhoot** [comment]
@nathanielc morgoth bin (v0.3.1) downloaded from github.com

**Comment by nathanielc** [comment]
@avdhoot OK, this issue has been fixed in master see #55 , but I haven't cut a new release since you will also need to use master branch of Kapacitor. Once Kapacitor's next release is cut, I'll cut a new Morgoth release as well.

**Comment by avdhoot** [comment]
@nathanielc  Thanks I will wait..
